"""Export the installed dependency closure for selected extras, never unrelated packages.

Run after installing the extras in a dedicated environment. This is a platform-
specific version lock, not a cross-platform resolver or a wheel hash lock.
"""

import argparse
from importlib.metadata import distribution
from pathlib import Path
import platform
import sys

from packaging.requirements import Requirement
from packaging.utils import canonicalize_name


def export(extras):
    pending = [("vigovbot", set(extras))]
    visited, versions = {}, {}
    while pending:
        name, enabled_extras = pending.pop()
        name = canonicalize_name(name)
        if name in visited and enabled_extras <= visited[name]:
            continue
        visited.setdefault(name, set()).update(enabled_extras)
        installed = distribution(name)
        if name != "vigovbot":
            versions[name] = installed.version
        for raw in installed.requires or []:
            requirement = Requirement(raw)
            if requirement.marker and not any(
                requirement.marker.evaluate({"extra": extra}) for extra in {"", *visited[name]}
            ):
                continue
            resolved = distribution(requirement.name)
            if requirement.specifier and not requirement.specifier.contains(resolved.version, prereleases=True):
                raise ValueError(f"Installed {requirement.name}=={resolved.version} does not satisfy {requirement}")
            pending.append((requirement.name, set(requirement.extras)))
    header = [
        "# Generated by scripts/export_lock.py; do not edit versions by hand.",
        f"# Python {platform.python_version()}; {sys.platform}; {platform.machine()}",
        f"# Extras: {','.join(sorted(extras))}",
        "# Install dependencies with -r, then install the project with --no-deps.",
    ]
    return "\n".join(header + [f"{name}=={version}" for name, version in sorted(versions.items())]) + "\n"


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--extras", required=True, help="Comma-separated pyproject extras")
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()
    content = export(args.extras.split(","))
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(content, encoding="utf-8")


if __name__ == "__main__":
    main()
